In [1]:
import pandas as pd
import requests

In [2]:
response =requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=59c99b99e117f2fb7fe8d219aed4bd9d&page=1")

In [3]:
pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity']]

,id,title,overview,release_date,popularity
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,56.3199
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,39.5995
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,21.1650
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.7852
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,16.5541
5,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,9.1789
6,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,23.7625
7,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,30.5181
8,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,10.7222
9,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,20.8912
10,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,31.2123
11,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,25.9689
12,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,27.1701
13,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,21.9181
14,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,49.9435
15,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,17.0245
16,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,23.8090
17,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,21.4692
18,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,11.2857
19,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.0121

In [4]:
df=pd.DataFrame()

In [5]:
for i in range(1,501):
  response =requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=59c99b99e117f2fb7fe8d219aed4bd9d&page={}".format(i))
  temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity']]
  df=pd.concat([df, temp_df], ignore_index=True)

In [6]:
df

,id,title,overview,release_date,popularity
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,56.3199
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,39.5995
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,21.1650
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.7852
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,16.5541
...,...,...,...,...,...
9995,10007,See No Evil,A group of delinquents are sent to clean the B...,2006-05-19,1.6774
9996,9278,Freejack,Time-traveling bounty hunters find a doomed ra...,1992-01-17,2.5997
9997,641790,Trauma Center,Lt. Wakes is a vengeful police detective deter...,2019-12-06,1.7734
9998,10063,The Breed,Brothers John and Matt have inherited an islan...,2006-05-17,2.0323
9999,615177,Coffee & Kareem,A Detroit cop reluctantly teams with his girlf...,2020-04-03,1.0303

In [7]:
df.shape

(10000, 5)

In [10]:
df.to_csv('Top movies.csv')